# Generated by Django 3.2.13 on 2022-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220612_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postviews',
            old_name='views',
            new_name='datedViews',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
